name: emulator

channels:
  - conda-forge

dependencies:
  - dask[complete]==2022.7.0
  - dask-expr
  - dask-jobqueue
  - dask-ml
  - jupyterlab>=3,<4
  - dask-labextension
  - jupyterlab-git
  - python-graphviz
  - gdal
  - pandas
  - numpy
  - matplotlib
  - joblib
  - rasterio
  - xarray
  - scikit-learn==1.2.2
  - rioxarray
  - geopandas
  - shapely
  - pip
  - zarr
  - pip:
     - pystemmusscope
