name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.9
  - dask[complete] 
  - jupyterlab
  - gdal
  - geopandas
  - dask-geopandas
  - matplotlib 
  - pip
  - pip:
    - dcachefs 
    - laspy[lazrs]

