name: jupyter_dask

dependencies:
  - python=3.9
  # pin Dask version until https://github.com/dask/distributed/pull/6841 is released
  - dask[complete]==2022.7.0
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - jupyterlab-git
  - gdal
  - xarray
  - rioxarray
  - xarray-spatial
  - matplotlib 
  - h5netcdf
  - zarr
  - pip
  - pip:
    - clustering-geodata-cubes
    - stac2dcache

