name: jupyter_dask

dependencies:
  - python=3.9
  - dask[complete] 
  - dask-jobqueue
  - jupyterlab>=3
  - dask-labextension
  - gdal
  - xarray
  - rioxarray
  - matplotlib 
  - h5netcdf
  - pip
  - pip:
    - stac2dcache

