name: jupyter_dask

channels:
  - conda-forge

dependencies:
  - python=3.9
  - dask[complete] 
  - jupyterlab
  - gdal
  - xarray
  - rioxarray
  - matplotlib 
  - pip
  - pip:
    - stackstac
    - pystac-client==0.3.2
    - stac2dcache

